### ISSUE TITLE
new function in PWM.h

### ISSUE THREAD

**Issue by trilu2000** [jp112sdl/HB-OU-MOT-SERVO#1]
Hi Jerome, i have proposed an additional function in dev-trilu for the DimmerControl - updatePhysical()
It makes use of the muliplier and characteristic flag and forwards them into PWM8 or PWM16.
I have recognized that you are using the DimmerControl in your HM-OU-MOT-SERVO sketch, but with a local NoPWM class.

If you ammend one function call into your class the travis check goes through and i can commit it to Asksin.

`pwms[i].param(speedMultiplier,characteristic);`
speedMultiplier and characteristics are uint8_t

**Comment by jp112sdl** [comment]
Hatte ich vorhin schon gleich gefixt, als die CI gemeckert hat ;) 
https://github.com/jp112sdl/HB-OU-MOT-SERVO/blob/5343077197b495d51ba9ab62ae55c54d294b2a35/HB-OU-MOT-SERVO.ino#L71

Aber trotzdem danke für den Hinweis, wär sonst vielleicht untergegangen 👍

**Comment by trilu2000** [comment]
sehr gerne und Danke fürs fixen.
